import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-screen flex items-center justify-center'>
        <p className='text-3xl text-center text-gray-700'><span className='font-bold text-4xl'>Detigo</span> <br/> Frontend Core Template</p>        
      </main>
    </div>
  )
}
